### ISSUE TITLE
Compiled Version 2.0 but ICE Supervisor is still showing Version 1.5.0

### ISSUE THREAD

**Issue by rhepstein1** [mdpnp/mdpnp#111]
I downloaded the 2.0 build and compiled, then opened the Ice Supervisor using simulated data.
The version shown on the screen is 1.5.0 not 2.0.
Did I do something wrong?

![OpenIce Screenshot showing version 1 5 0](https://github.com/user-attachments/assets/48ced738-c918-47af-b887-1333dcca7809)

**Comment by simonkelly1973** [comment]
Hello.

No, you didn't do anything wrong.  That version number is hard coded into the UI display.  It hasn't been updated, which is just an oversight when making the release.

**Comment by rhepstein1** [comment]
Thank you.
