### ISSUE TITLE
Background color in the device display window

### ISSUE THREAD

**Issue by rhepstein1** [mdpnp/mdpnp#121]
Is it possible to change the background color in the window displaying the monitor view (waveforms and numerics), like one can do in the terminal window?

Some of the waveforms are virtually invisible, especially on a small screen.

**Comment by simonkelly1973** [comment]
Not at the moment, no.  I'm nor aware that anyone has ever asked for that before.  We'll have a look how simple it would be.

**Comment by rhepstein1** [comment]
Red on black is nearly invisible as is dark green on black.
I’m using a 7” portable screen to see what is going on when connecting to patient montitor as I have to type in commands and it’s useful to be able to check that the data are coming over.
A white background would be preferred.

If this output is going to the terminal screen, then:

“In Java you would a System.out.println("\033[107m\033[30m") during startup of the application.”
https://stackoverflow.com/questions/38900822/set-terminal-background-color-with-java


Rich

From: Simon Kelly ***@***.***>
Sent: Tuesday, September 24, 2024 3:08 PM
To: mdpnp/mdpnp ***@***.***>
Cc: Epstein, Richard ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [mdpnp/mdpnp] Background color in the device display window (Issue #121)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Not at the moment, no. I'm nor aware that anyone has ever asked for that before. We'll have a look how simple it would be.

**Comment by simonkelly1973** [comment]
So this is configurable reasonably easily for the background color.  The foreground is a different question.

The "device panels" are styled using CSS, which is similar to how styling works in HTML.  You can edit the following file

interop-lab/demo-apps/src/main/resources/org/mdpnp/apps/device/demo-guis-javafx.css

The precise part you need to edit depends on the "panel" that you want to change.  Fortunately it should be fairly clear from the descriptive names of the elements where to look.  For example, for ECG, the panel is called

```
.electro-cardiogram-panel {
  -fx-background-color: yellow;
}
```
as you can see on line 17 of the file.  Editing the background color to yellow as shown here gives you a panel like this

![image](https://github.com/user-attachments/assets/851fb7a6-0fc4-45c2-b7d7-c5723b989b5a)

Notice that the pleth panel above is unaffected, as that has a different style class.

The foreground color of the waveforms is not currently controlled in CSS.  To edit that, you need to edit

interop-lab/demo-apps/src/main/java/org/mdpnp/apps/device/ElectroCardioGramPanel.java

and change the return value of "getWaveformPaint()".  For ECG, this is "GREEN" at the moment, but there are a long list of alternative color constants defined that you could use instead.

However hopefully changing the background color is sufficient for now.
