### ISSUE TITLE
Question about the life tick connection with Philips Intellivue monitors

### ISSUE THREAD

**Issue by rhepstein1** [mdpnp/mdpnp#128]
I need to split the serial output from a Philips monitor to 2 separate devices with the life tick transmitted back to Intellivue supplied by only one of the 2 computers (otherwise, Intellivue will shut down after a few minutes). I've tested this architecture successfully with another data recording program (VitalRecorder) running on the two computers with the TXD line from the 2nd computer's serial interface disconnected (i.e., it receives the output from Intellivue and the other computer periodically tells Intellivue to keep transmitting). Would this present any issues on the OpenIce side if it were to only receive the transmitted data from Intellivue? Or will it (hopefully) just digest everything that comes across?

Can the same approach can be applied GE and Drager monitors currently supported by OpenICE?

**Comment by simonkelly1973** [comment]
I think that's probably winning a prize for "something we've never tried to do before".  Although perhaps we have and I just don't know about it.

It's quite difficult to envisage exactly what the consequences of not having a working transmit line on a serial connection from an OpenICE device would be.  A few things spring to mind.

1. OpenICE might expect to do some negotiation with the Intellivue device.  If that were not working as expected, the device interface might just quit or not try to start publishing date.
2. The expected data that OpenICE might be expecting to receive as a result of what it transmits might be out of sync with what it thinks it has asked for.

Ultimately, what will happen also depends on whether the software can detect the fact that a genuine transmit failure has occured.  There are quite a few layers there - OpenICE tries to publish something on the serial port.  That's a request to a Java serial port driver library.  That library passes it to a lower level library (still pure Java) and eventually it will end up at the OS/Hardware level.  Whether a failure to transmit is genuinely detectable by virtue of a "break in the cable" is difficult to know - and it's also difficult to know how such an error would be propogated all the way back up through the layers to OpenICE itself.

I think the shorter version of that reply is "you'll have to try it and see".  Do let us know though - it's an interesting question.

**Comment by rhepstein1** [comment]
I’ll let you know. It worked fine with VitalRecorder. My serial to usb cable has LEDs that show transmission on the various lines originating from either side of the connection. There appeared to be collisions when both computers were transmitting that resulted in the interface shutting down. The way that Intellivue works is that when the control signal stops it will continue to transmit for a minute or two before the outbound interface shuts down. I was initially confused by no apparent signal coming from the serial port when I checked with a multimeter. Attaching a digital oscilloscope in parallel when VitalRecorder was running and then the usb cable on the computer side was disconnected showed what was going on. At least for VitalRecorder, it appears that all the negotiation takes place on the monitor side and the client software just slurps up whatever is sent. I’m crossing my fingers that OpenIce will exhibit similar behavior.

This has some practical implications beyond the research project I’m working on. Some monitors only have a single serial port for output, which may be in use, for example, to connect to the EHR. If the signal can be split, that would allow tapping the signal. In the past, I’ve sometimes had to build an op amp circuit to boost low voltage signals, but I don’t think this will be necessary here as the signals are strong.

It also would be of potential use if one wanted to present different views of the same real-time monitor data simultaneously to two groups, for example, to evaluate user interface designs. Of course, one could also do that via simulated or replay of captured data, but it might be desirable to have a live feed for some studies.

There are likely many other use cases.


From: Simon Kelly ***@***.***>
Sent: Friday, October 25, 2024 11:07 AM
To: mdpnp/mdpnp ***@***.***>
Cc: Epstein, Richard ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [mdpnp/mdpnp] Question about the life tick connection with Philips Intellivue monitors (Issue #128)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

I think that's probably winning a prize for "something we've never tried to do before". Although perhaps we have and I just don't know about it.

It's quite difficult to envisage exactly what the consequences of not having a working transmit line on a serial connection from an OpenICE device would be. A few things spring to mind.

  1.  OpenICE might expect to do some negotiation with the Intellivue device. If that were not working as expected, the device interface might just quit or not try to start publishing date.
  2.  The expected data that OpenICE might be expecting to receive as a result of what it transmits might be out of sync with what it thinks it has asked for.

Ultimately, what will happen also depends on whether the software can detect the fact that a genuine transmit failure has occured. There are quite a few layers there - OpenICE tries to publish something on the serial port. That's a request to a Java serial port driver library. That library passes it to a lower level library (still pure Java) and eventually it will end up at the OS/Hardware level. Whether a failure to transmit is genuinely detectable by virtue of a "break in the cable" is difficult to know - and it's also difficult to know how such an error would be propogated all the way back up through the layers to OpenICE itself.

I think the shorter version of that reply is "you'll have to try it and see". Do let us know though - it's an interesting question.

**Comment by rhepstein1** [comment]
It is possible to split the signal and collect data on the VitalRecorder and OpenICE from Philips IntelliVue monitors.
OpenICE will negotiate the connection, it has to have the full RXD-TXD-GND connection, at least until the connection is establshed. After that, OpenICE doesn't care and will continue to process the stream as long as the monitor is trransmitting.

VitalRecorder doesn't appear to care about negotiating a connection. So if you connect OpenICE with a fully configured cable to the Philips monitor to start the data flow, then connect cable with only the TXD-GND connection from the monitor to VitalRecorder, it will acquire the data.

Alternatively, you can start the connection on OpenICE then disconnect the TXD line from the computer running OpenICE and use a fully connected cable to another computer running VitalRecorder. The latter will keep the data flow running and disconnecting the TXD line from OpenIce prevents the collisions that would otherwise occur. You have a minute or so to do the switch as the lifetick is processed intermittently.

It should also work with 2 computers running OpenICE starting one with the full connection, then disconnecting the TXD line from the OpenIce computer and connecting a second computer running OpenIce with a fully connected cable. That 2nd computer will keep the data flow running from the monitor.

The key points when splitting the serial output from a Philips monitor are:
1. The computer running OpenICE has to negotiate the connection to the Philips monitor, but once established, the connection is set and doesn't need to be refreshed
2. Only one computer can be transmitting life ticks to the Philips monitor, which will keep the data flowing from the device. If the life tick stops, the monitor stops transmitting
3. Once OpenIce establishes the connection, as long as the data keeps flowing, the TXD ;line from the computer running OpenICE is not needed to continue processing the data
4. When using OpenIce and using VitalRecorder, the simplest approach is to use the fully connected cable with OpenIce and the TXD-GND cable from the monitor with VitalRecorder
5.  Behavior of data logging programs other than VitalRecorder have not been tested.
